# Generated by Django 6.0 on 2026-01-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CEE_Quiz', '0001_initial'),
    ]

    operations = [
    ]
