# Generated by Django 6.0 on 2026-01-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEE_Quiz', '0002_auto_20260101_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=255),
        ),
    ]
