# Generated by Django 6.0 on 2025-12-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEE_Quiz', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('score', models.FloatField()),
                ('total_questions', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
