# Generated by Django 6.0 on 2025-12-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CEE_Quiz', '0004_testresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='total_questions',
            new_name='total_attempted',
        ),
    ]
